### ISSUE TITLE
Error checking needed

### ISSUE THREAD

**Issue by jungle-boogie** [fazalmajid/edgewalker#1]
Hi,

Thanks for creating this script. Keep up the good work.

On first pass, it looks like there needs to be some error checks. See this example:

```
$ doas ./edgewalker.sh
What is the FQDN hostname to use? opti3020.in.example.net
Secret: 3rd2U4kPM5U8YubK
setting up sysctl.conf
Setting up PF
Primary net interface re0 192.168.30.33
fe80::7a45:c4ff:fe07:6621%re0
Restarting PF
/etc/pf.conf:9: syntax error
/etc/pf.conf:11: syntax error
/etc/pf.conf:15: syntax error
/etc/pf.conf:20: syntax error
/etc/pf.conf:22: syntax error
/etc/pf.conf:24: syntax error
pfctl: Syntax error in config file: pf rules not loaded
rm: lets-encrypt-x3-cross-signed.pem*: No such file or directory
./edgewalker.sh[309]: wget: not found
cp: lets-encrypt-x3-cross-signed.pem: No such file or directory
Setting up httpd
httpd(ok)
httpd(ok)
Setting up OpenIKEd
Getting LE certificates
Generating private keys
vpn

Renewing certificates
Renewing certificates
vpn
Parsing account key...
Traceback (most recent call last):
  File "acme_tiny.py", line 197, in <module>
    main(sys.argv[1:])
  File "acme_tiny.py", line 193, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args
.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "acme_tiny.py", line 75, in get_crt
    out = _cmd(["openssl", "rsa", "-in", account_key, "-noout", "-text"], err_msg="OpenSSL Error")
  File "acme_tiny.py", line 28, in _cmd
    raise IOError("{0}\n{1}".format(err_msg, err))
OSError: OpenSSL Error
b'unable to load Private Key\n9310926458816:error:09FFF06C:PEM routines:CRYPTO_internal:no start line:/usr/src
/lib/libcrypto/pem/pem_lib.c:694:Expecting: ANY PRIVATE KEY\n'
Applying sysctl settings
net.inet.ip.forwarding: 1 -> 1
net.inet.ip.redirect: 0 -> 0
net.inet.ipcomp.enable: 1 -> 1
net.inet.ah.enable: 1 -> 1
net.inet.esp.enable: 1 -> 1
net.inet.esp.udpencap: 1 -> 1
Starting OpenIKEd
iked(failed)
Enabling SSL on HTTPd
httpd(ok)
httpd(ok)
quirks-3.494 signed on 2020-12-01T18:07:31Z
iOS/iPadOS/macOS VPN config QR code
```

So there's a few things:
* pf rejects the rules
* wget isn't installed
* There's some python issue with acme_tiny.py
* iked failed to start

Note: I didn't edit X509 or USERNAME. Would this have caused the failures above, though?

**Comment by jungle-boogie** [comment]
Is there some reason you're not using [rcctl ](https://man.openbsd.org/rcctl.8)to enable, start, stop services?

example:
```
/etc/rc.d/httpd stop
/etc/rc.d/httpd start
```

**Comment by jungle-boogie** [comment]
You're using pkg_add already:
`pkg_add libqrencode` 

You could move this at the top (or near) and also include `wget`

**Comment by fazalmajid** [comment]
Thank you for reporting this. I have been using Vultr VMs for the last testing, mostly because I don't have to worry about NAT traversal for the Let's Encrypt negotiation, and it didn't occur to me that their images would have extra stuff a vanilla OpenBSD install wouldn't have, like wget or python3.

Regarding the PF error, it's because you have both IPv4 and IPv6 addresses and I didn't test the AWK script that gets the main IP on a system that has both.

The OpenSSL error suggests you did not use a valid Let's Encrypt account key, or more likely you used one in the JWK format used by Certbot rather than the PEM format used by Acme-Tiny and OpenSSL. Can you confirm? A JWK key would start with a `{`, a PEM key would start with `-----BEGIN RSA PRIVATE KEY-----`.

In any case, I pushed some fixes, can you see if they help?

**Comment by jungle-boogie** [comment]
Hi,

Sorry for the late reply.

I like the changes you did. Perhaps one small critique I could make would be to print out a message of what packages are being installed. Maybe something like "checking to see if wget is installed" and/or "installing wget, python3"

> The OpenSSL error suggests you did not use a valid Let's Encrypt account key

That's correct. I think I just typed some random characters in and pressed ^D. So that looks like a failure on `acme_tiny.py` part, but it's expected, since the key isn't legitimate.

Thanks again for the script!
